FROM node:lts-bullseye

WORKDIR /usr/src/app

COPY . .
EXPOSE 5557

RUN chown -R node /usr/src/app
USER node
RUN npm i tsx @prisma/client
RUN npx prisma generate

CMD ["npx", "tsx", "./src/app/server.ts"]